[2024-11-17T13:56:07.284+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:07.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:07.312+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:07.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:07.529+0000] {processor.py:925} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:08.973+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:08.972+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T13:56:09.153+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:09.148+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-11-18 00:00:00+00:00, run_after=2024-11-19 00:00:00+00:00
[2024-11-17T13:56:09.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 2.196 seconds
[2024-11-17T13:56:30.594+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:30.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:30.608+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:30.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:30.664+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:30.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:30.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:30.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.163 seconds
[2024-11-17T13:56:31.830+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:31.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:31.851+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:31.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:31.931+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:31.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:31.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:32.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.267 seconds
[2024-11-17T13:56:33.046+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:33.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:33.117+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:33.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:33.183+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:33.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:33.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:33.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.411 seconds
[2024-11-17T13:56:34.256+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:34.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:34.272+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:34.269+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:34.325+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:34.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:34.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:34.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.233 seconds
[2024-11-17T13:56:35.334+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:35.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:35.353+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:35.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:35.371+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:35.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 56
    task_id=
    ^^^^^^^^
SyntaxError: expected argument value expression
[2024-11-17T13:56:35.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:35.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.128 seconds
[2024-11-17T13:56:36.473+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:36.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:36.501+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:36.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:36.647+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:36.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:36.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:36.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.349 seconds
[2024-11-17T13:56:37.562+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:37.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:37.573+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:37.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:37.677+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:37.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:37.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:37.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.229 seconds
[2024-11-17T13:56:38.599+0000] {processor.py:186} INFO - Started process (PID=286) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:38.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:38.623+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:38.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:38.748+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:38.721+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:38.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:39.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.504 seconds
[2024-11-17T13:56:40.076+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:40.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:40.107+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:40.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:40.262+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:40.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:40.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:40.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.823 seconds
[2024-11-17T13:56:42.358+0000] {processor.py:186} INFO - Started process (PID=296) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:42.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:42.372+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:42.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:42.388+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:42.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 58
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-11-17T13:56:42.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:42.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.308 seconds
[2024-11-17T13:56:42.995+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:43.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:43.110+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:43.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:43.131+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:43.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 58
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-11-17T13:56:43.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:43.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.801 seconds
[2024-11-17T13:56:47.093+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:47.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:48.294+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:48.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:49.120+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:49.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:49.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:49.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 3.221 seconds
[2024-11-17T13:56:53.064+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:53.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:56:53.161+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:53.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:53.864+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:56:53.736+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:56:53.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:56:54.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 1.941 seconds
[2024-11-17T13:57:12.144+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:12.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:12.278+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:12.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:12.592+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:12.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:57:12.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:12.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.678 seconds
[2024-11-17T13:57:13.562+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:13.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:13.658+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:13.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:13.817+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:13.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:57:13.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:14.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.530 seconds
[2024-11-17T13:57:15.162+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:15.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:15.183+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:15.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:15.493+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:15.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:57:15.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:15.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.604 seconds
[2024-11-17T13:57:16.452+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:16.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:16.463+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:16.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:16.637+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:16.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:57:16.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:17.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.631 seconds
[2024-11-17T13:57:17.987+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:17.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:18.005+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:18.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.028+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:18.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61
    load_task >
               ^
SyntaxError: invalid syntax
[2024-11-17T13:57:18.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.147 seconds
[2024-11-17T13:57:18.352+0000] {processor.py:186} INFO - Started process (PID=377) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:18.370+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:18.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.384+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:18.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61
    load_task >>
                ^
SyntaxError: invalid syntax
[2024-11-17T13:57:18.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.205 seconds
[2024-11-17T13:57:18.638+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:18.681+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:18.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.701+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:18.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61
    load_task >> 
                 ^
SyntaxError: invalid syntax
[2024-11-17T13:57:18.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:18.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.201 seconds
[2024-11-17T13:57:20.121+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:20.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:20.134+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:20.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:20.282+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:20.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:57:20.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:20.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.661 seconds
[2024-11-17T13:57:22.955+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:22.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:22.965+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:22.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:23.092+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:23.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 55, in <module>
    snowflake_task = SnowflakeOperator(
                     ^^^^^^^^^^^^^^^^^
NameError: name 'SnowflakeOperator' is not defined
[2024-11-17T13:57:23.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:23.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.530 seconds
[2024-11-17T13:57:26.612+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:26.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:57:27.448+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:27.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:29.175+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:57:29.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T13:57:29.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:57:29.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 3.162 seconds
[2024-11-17T13:58:00.143+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:58:00.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:58:00.163+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:58:00.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:58:00.237+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:58:00.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T13:58:00.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:58:00.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.175 seconds
[2024-11-17T13:58:30.983+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:58:31.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:58:31.047+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:58:31.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:58:31.092+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:58:31.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T13:58:31.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:58:31.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.436 seconds
[2024-11-17T13:59:01.853+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:59:01.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T13:59:01.859+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:59:01.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:59:01.906+0000] {logging_mixin.py:190} INFO - [2024-11-17T13:59:01.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T13:59:01.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T13:59:01.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.146 seconds
[2024-11-17T14:03:46.459+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:03:46.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:03:46.624+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:03:46.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:03:46.813+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:03:46.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:03:46.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:03:47.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.830 seconds
[2024-11-17T14:04:33.099+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:04:33.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:04:33.283+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:04:33.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:04:33.554+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:04:33.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:04:33.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:04:33.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.693 seconds
[2024-11-17T14:07:09.045+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:07:09.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:07:09.059+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:07:09.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:07:09.114+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:07:09.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:07:09.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:07:09.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.187 seconds
[2024-11-17T14:07:43.733+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:07:43.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:07:43.740+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:07:43.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:07:43.775+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:07:43.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:07:43.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:07:43.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.084 seconds
[2024-11-17T14:08:14.742+0000] {processor.py:186} INFO - Started process (PID=286) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:14.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:08:14.758+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:08:14.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:14.782+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:08:14.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:08:14.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:14.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.095 seconds
[2024-11-17T14:08:39.774+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:39.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:08:39.783+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:08:39.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:39.847+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:08:39.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 57, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:08:39.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:39.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.142 seconds
[2024-11-17T14:08:44.999+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:45.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:08:45.010+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:08:45.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:45.070+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:08:45.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:08:45.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:08:45.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.197 seconds
[2024-11-17T14:09:15.266+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:09:15.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:09:15.271+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:09:15.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:09:15.292+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:09:15.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:09:15.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:09:15.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.064 seconds
[2024-11-17T14:10:02.794+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:10:02.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:10:02.941+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:10:02.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:10:03.003+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:10:02.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:10:03.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:10:03.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.390 seconds
[2024-11-17T14:10:36.344+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:10:36.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T14:10:37.063+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:10:37.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T14:10:38.224+0000] {logging_mixin.py:190} INFO - [2024-11-17T14:10:38.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T14:10:38.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T15:33:59.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 5003.846 seconds
[2024-11-17T15:34:33.583+0000] {processor.py:186} INFO - Started process (PID=482) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T15:34:33.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T15:34:33.895+0000] {logging_mixin.py:190} INFO - [2024-11-17T15:34:33.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T15:34:35.063+0000] {logging_mixin.py:190} INFO - [2024-11-17T15:34:34.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T15:34:35.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T15:34:36.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 4.047 seconds
[2024-11-17T16:10:02.783+0000] {processor.py:186} INFO - Started process (PID=518) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T16:10:02.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T16:10:02.795+0000] {logging_mixin.py:190} INFO - [2024-11-17T16:10:02.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T16:10:02.871+0000] {logging_mixin.py:190} INFO - [2024-11-17T16:10:02.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T16:10:02.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T16:10:02.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.208 seconds
[2024-11-17T16:15:30.480+0000] {processor.py:186} INFO - Started process (PID=540) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T16:15:30.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T16:15:30.491+0000] {logging_mixin.py:190} INFO - [2024-11-17T16:15:30.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T16:15:30.519+0000] {logging_mixin.py:190} INFO - [2024-11-17T16:15:30.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T16:15:30.521+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T16:15:30.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.089 seconds
[2024-11-17T16:16:09.961+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:11:02.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:11:03.133+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:11:03.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:11:03.433+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:11:03.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:11:03.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:11:03.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 3296.217 seconds
[2024-11-17T17:26:51.997+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:26:52.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:26:52.016+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:26:52.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:26:52.272+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:26:52.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:26:52.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:26:52.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.458 seconds
[2024-11-17T17:27:22.730+0000] {processor.py:186} INFO - Started process (PID=667) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:27:22.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:27:22.738+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:27:22.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:27:22.768+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:27:22.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:27:22.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:27:22.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.102 seconds
[2024-11-17T17:27:53.856+0000] {processor.py:186} INFO - Started process (PID=708) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:27:53.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:27:53.872+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:27:53.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:27:53.924+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:27:53.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:27:53.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:27:53.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.159 seconds
[2024-11-17T17:28:24.093+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:28:24.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:28:24.099+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:28:24.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:28:24.124+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:28:24.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:28:24.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:28:24.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.069 seconds
[2024-11-17T17:28:54.293+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:28:54.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:28:54.301+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:28:54.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:28:54.333+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:28:54.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:28:54.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:28:54.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.136 seconds
[2024-11-17T17:29:25.158+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:29:25.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:29:25.164+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:29:25.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:29:25.192+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:29:25.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:29:25.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:29:25.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.076 seconds
[2024-11-17T17:29:56.175+0000] {processor.py:186} INFO - Started process (PID=872) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:29:56.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:29:56.182+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:29:56.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:29:56.208+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:29:56.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:29:56.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:29:56.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.075 seconds
[2024-11-17T17:30:27.100+0000] {processor.py:186} INFO - Started process (PID=913) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:30:27.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:30:27.109+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:30:27.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:30:27.136+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:30:27.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:30:27.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:30:27.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.080 seconds
[2024-11-17T17:30:57.865+0000] {processor.py:186} INFO - Started process (PID=954) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:30:57.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:30:57.875+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:30:57.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:30:57.899+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:30:57.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:30:57.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:30:57.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.082 seconds
[2024-11-17T17:31:28.700+0000] {processor.py:186} INFO - Started process (PID=995) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:31:28.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:31:28.711+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:31:28.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:31:28.732+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:31:28.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:31:28.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:31:28.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.088 seconds
[2024-11-17T17:31:59.739+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:31:59.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:31:59.748+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:31:59.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:31:59.855+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:31:59.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:31:59.859+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:31:59.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.218 seconds
[2024-11-17T17:32:31.037+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:32:31.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:32:31.054+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:32:31.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:32:31.258+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:32:31.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:32:31.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:32:31.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.288 seconds
[2024-11-17T17:33:01.394+0000] {processor.py:186} INFO - Started process (PID=1118) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:33:01.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:33:01.401+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:33:01.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:33:01.433+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:33:01.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:33:01.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:33:01.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.089 seconds
[2024-11-17T17:33:32.307+0000] {processor.py:186} INFO - Started process (PID=1159) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:33:32.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:33:32.313+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:33:32.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:33:32.332+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:33:32.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:33:32.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:33:32.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.063 seconds
[2024-11-17T17:34:03.045+0000] {processor.py:186} INFO - Started process (PID=1199) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:34:03.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:34:03.052+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:34:03.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:34:03.071+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:34:03.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:34:03.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:34:03.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.064 seconds
[2024-11-17T17:34:33.856+0000] {processor.py:186} INFO - Started process (PID=1240) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:34:33.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:34:33.863+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:34:33.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:34:33.879+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:34:33.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:34:33.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:34:33.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.059 seconds
[2024-11-17T17:35:04.612+0000] {processor.py:186} INFO - Started process (PID=1281) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:35:04.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:35:04.618+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:35:04.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:35:04.638+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:35:04.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:35:04.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:35:04.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.063 seconds
[2024-11-17T17:35:35.589+0000] {processor.py:186} INFO - Started process (PID=1322) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:35:35.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:35:35.596+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:35:35.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:35:35.615+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:35:35.612+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:35:35.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:35:35.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.065 seconds
[2024-11-17T17:36:06.483+0000] {processor.py:186} INFO - Started process (PID=1363) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:36:06.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:36:06.488+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:36:06.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:36:06.521+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:36:06.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:36:06.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:36:06.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.076 seconds
[2024-11-17T17:36:37.377+0000] {processor.py:186} INFO - Started process (PID=1404) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:36:37.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:36:37.385+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:36:37.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:36:37.402+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:36:37.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:36:37.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:36:37.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.061 seconds
[2024-11-17T17:37:07.511+0000] {processor.py:186} INFO - Started process (PID=1445) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:37:07.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:37:07.517+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:37:07.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:37:07.540+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:37:07.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:37:07.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:37:07.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.066 seconds
[2024-11-17T17:37:37.700+0000] {processor.py:186} INFO - Started process (PID=1486) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:37:37.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:37:37.706+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:37:37.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:37:37.729+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:37:37.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:37:37.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:37:37.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.065 seconds
[2024-11-17T17:38:07.855+0000] {processor.py:186} INFO - Started process (PID=1527) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:38:07.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:38:07.860+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:38:07.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:38:07.876+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:38:07.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:38:07.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:38:07.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.059 seconds
[2024-11-17T17:38:38.708+0000] {processor.py:186} INFO - Started process (PID=1568) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:38:38.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:38:38.714+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:38:38.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:38:38.732+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:38:38.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:38:38.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:38:38.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.062 seconds
[2024-11-17T17:39:09.667+0000] {processor.py:186} INFO - Started process (PID=1609) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:39:09.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:39:09.671+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:39:09.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:39:09.690+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:39:09.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:39:09.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:39:09.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.064 seconds
[2024-11-17T17:39:40.549+0000] {processor.py:186} INFO - Started process (PID=1650) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:39:40.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:39:40.559+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:39:40.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:39:40.593+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:39:40.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:39:40.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:39:40.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.160 seconds
[2024-11-17T17:40:11.422+0000] {processor.py:186} INFO - Started process (PID=1691) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:40:11.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:40:11.429+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:40:11.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:40:11.453+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:40:11.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:40:11.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:40:11.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.074 seconds
[2024-11-17T17:40:42.144+0000] {processor.py:186} INFO - Started process (PID=1732) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:40:42.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:40:42.149+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:40:42.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:40:42.171+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:40:42.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:40:42.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:40:42.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.069 seconds
[2024-11-17T17:41:13.197+0000] {processor.py:186} INFO - Started process (PID=1773) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:41:13.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:41:13.203+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:41:13.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:41:13.228+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:41:13.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:41:13.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:41:13.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.071 seconds
[2024-11-17T17:41:44.240+0000] {processor.py:186} INFO - Started process (PID=1814) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:41:44.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:41:44.247+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:41:44.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:41:44.275+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:41:44.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:41:44.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:41:44.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.081 seconds
[2024-11-17T17:42:15.121+0000] {processor.py:186} INFO - Started process (PID=1855) to work on /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:42:15.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/3-taskflow_api.py for tasks to queue
[2024-11-17T17:42:15.126+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:42:15.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:42:15.151+0000] {logging_mixin.py:190} INFO - [2024-11-17T17:42:15.144+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/3-taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3-taskflow_api.py", line 61, in <module>
    load_task >> print_task
    ~~~~~~~~~~^^~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 153, in set_upstream
    operator.set_upstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 271, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_relative'
[2024-11-17T17:42:15.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/3-taskflow_api.py
[2024-11-17T17:42:15.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/3-taskflow_api.py took 0.071 seconds
